apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-movie
spec:
  serviceName: 'postgres-movie'
  selector:
    matchLabels:
      app: postgres-movie
  replicas: {{ .Values.db_movies.replicaCount }}
  template:
    metadata:
      labels:
        app: postgres-movie
    spec:
      containers:
      - name: postgres-movie
        image: "{{ .Values.db_movies.image.repository }}:{{ .Values.db_movies.image.tag | default .Chart.AppVersion }}"
        env:
        - name: POSTGRES_DB
          value: "movie_db_{{ .Values.namespace }}"
        envFrom:
          - secretRef:
              name: postgres-movie-credentials
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-movie-volume
        ports:
        - containerPort: 5432
  volumeClaimTemplates:
  - metadata:
      name: postgres-movie-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi