apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-movie-config
data:
  HOST: "postgres-movie-service.{{ .Values.namespace }}.svc.cluster.local"
  PORT: "5432"
  NAME: "movie_db_.{{ .Values.namespace }}"